export enum ATTACHMENTS {
    SET_FILTER = 'SET_FILTER',
    SET_ATTACHMENTS = 'SET_ATTACHMENTS',
    ADD_ATTACHMENT = 'ADD_ATTACHMENT',
    FETCH_REQUEST_ATTACHMENTS = 'FETCH_REQUEST_ATTACHMENTS',
    RECORD_ATTACHMENT = 'RECORD_ATTACHMENT',
    REMOVE_ATTACHMENT = 'REMOVE_ATTACHMENT',
}